name: Build FMILibrary

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            test-task: linuxX64Test
            container: dockcross/linux-x64:latest  # glibc compatibile con KN
          - os: macos-latest
            test-task: macosArm64Test
            container: ""
          - os: windows-latest
            test-task: mingwX64Test
            container: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build FMILibrary
        run: ./gradlew cmakeBuild

      - name: Run tests
        run: ./gradlew :fmu-kt:${{ matrix.test-task }}

      - name: Upload install dir
        uses: actions/upload-artifact@v4
        with:
          name: fmilib-${{ matrix.os }}
          path: fmilib/build/fmilib-install/